# SITE CONFIGURATION
baseurl: "/"
url: "https://lab.codingblocks.com/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  url: "https://lab.codingblocks.com/"
  # Meta
  title: Coding Blocks Labs
  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
    <p>
      Coding Blocks Labs is an open source playground supported by Coding Blocks
    </p>

  header_text_feature_image:
  footer_text: >
   Maintained with ‚ù§ by <a href="http://cb.lk"> Coding Blocks </a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "CodingBlocksIndia"
  flickr:
  gitlab:
  github: "coding-blocks"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "CodingBlocksIN"
  wordpress:
  youtube: "CodingBlocksIndia"

  # Scripts
  google_analytics: "UA-83327907-3"
  disqus_shortname: "codingblocks"
  katex: true # Enable if using math markup
  search: true # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Detailed Information"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "projects/page/:num"

# Pages
include:
 - _pages

collections:
  ideas:
    output: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: :compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
