# Harmony Jekyll theme general configurations 

# Base URL
#baseurl: /harmony

# Site live URL
url: http://lab.codingblocks.com
#url: http://localhost:4000

# Localhost 
# url: http://127.0.0.1:4000  

# Harmony theme configuration. Please change accordingly.
harmony:
  name: Coding Blocks Labs
  # Little description about your site
  description: An Open Source Projects playground
  # 'meta_description:' Write an awesome description for your new site here.
  # It will appear in your document head meta (for Google search results) and 
  # in your feed.xml site description.
  meta_description: > # 
   Coding Blocks Labs - An Open Source Projects Playground
   Students can take part in these open source projects, or
   start their own ones.
  basetheme: redish # pre defined thmes are darken, blue-water, redish.
  author: # Author details
    name: Arnav Gupta
    email: arnav@codingblocks.com
    url: http://codingblocks.com

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-83327907-3

  # Profile links, leave blank to ignore
  social: 
    github: coding-blocks
    twitter: codingblocksIN
    facebook: codingblocksindia
#    gplus: +GayanVirajith
#    dribble: gayan
#    pinterest:
  # Toggle disclaimer in footer
  show_disclaimer: true

# Conversion / Build settings 
markdown:    kramdown
# This is how you put pygments config in jekyll 2.0 instead of pygments: true
highlighter: pygments 

# Permalinks
permalink:        pretty

exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

collections:
  ideas:
    output: true

# Sass conversion configs
sass:
    sass_dir: assets/css/_sass
    style: :compressed
